/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.diffplug.spotless") version "6.21.0"
}

spotless {
    // Formatting for Java code (as an example)
    java {
        googleJavaFormat("1.10.0")
    }

    // Formatting for JavaScript or other files using Prettier:
    format("misc") {
        target("src/**/*.js", "src/**/*.ts", "src/**/*.css", "src/**/*.html")
        prettier().config(mapOf("singleQuote" to true))
    }
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")
    
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.test {
	useJUnit()
	testLogging {
		events("passed", "skipped", "failed")
	}
}